
[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-steputils"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-utils"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-xcode"

[[constraint]]
  branch = "master"
  name = "github.com/fullsailor/pkcs7"

[[constraint]]
  name = "github.com/hashicorp/go-version"
  version = "1.2.1"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "github.com/ryanuber/go-glob"
  version = "1.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.6.1"

[[constraint]]
  name = "golang.org/x/text"
  version = "0.3.3"

[[constraint]]
  branch = "master"
  name = "howett.net/plist"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/xcode-project"
